-- 001_init.sql — 初期スキーマ(8テーブル)
--
-- このファイルが「真実の源」。db/schema.sql は pg_dump による生成物(参照用)。
--
-- 方針: インデックスは PK / UNIQUE 以外あえて張らない。
--       遅いクエリを EXPLAIN ANALYZE で観測してから張る(002以降で追加)。
--
-- BEGIN/COMMIT は書かない: トランザクションは scripts/migrate.sh が
-- --single-transaction で管理する(適用履歴のINSERTと本体を同一Txにするため)。
--
-- 前提: 全PKは GENERATED **BY DEFAULT** AS IDENTITY にしている。
--   理由: CSVバルクロードで id を明示投入するため(ALWAYS だと COPY が拒否する)。
--   代償: アプリが誤って id を指定しても DB は拒否しない(仕組み→規律への妥協)。
--   前提が変わる箇所: バルクロードをやめるなら ALWAYS に戻し、仕組みで守ること。
--   投入後は setval() でシーケンスを max(id) に進める(scripts/load.sh が担当)。

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    prefecture  TEXT NOT NULL,              -- 集計クエリの練習用
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_addresses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    label        TEXT NOT NULL,              -- '自宅', '実家' など
    postal_code  TEXT NOT NULL,
    prefecture   TEXT NOT NULL,
    line1        TEXT NOT NULL,
    line2        TEXT
);

CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    parent_id  BIGINT REFERENCES categories(id)  -- 再帰CTEの練習用に階層化
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT NOT NULL REFERENCES categories(id),
    name         TEXT NOT NULL,
    description  TEXT,
    price_jpy    INTEGER NOT NULL CHECK (price_jpy >= 0),
    stock        INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    is_active    BOOLEAN NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key UUID NOT NULL UNIQUE,   -- リトライ二重登録防止。INSERT先行でUNIQUE違反を捕まえる方式
    user_id     BIGINT NOT NULL REFERENCES users(id),
    status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')),
    total_jpy   INTEGER NOT NULL CHECK (total_jpy >= 0),  -- 非正規化: order_itemsの合計と一致検証クエリも練習になる
    shipping_fee_jpy INTEGER NOT NULL DEFAULT 0 CHECK (shipping_fee_jpy >= 0),  -- 1注文=1配送の前提。分割配送対応時はshipmentsへ分離(v2)
    -- 配送先スナップショット: 注文時にuser_addressesからコピー。引っ越しの影響を受けない
    ship_to_postal_code TEXT NOT NULL,
    ship_to_prefecture  TEXT NOT NULL,
    ship_to_line1       TEXT NOT NULL,
    ship_to_line2       TEXT,
    ordered_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders(id),
    product_id      BIGINT NOT NULL REFERENCES products(id),
    quantity        INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_jpy  INTEGER NOT NULL CHECK (unit_price_jpy >= 0)  -- 注文時点の価格スナップショット
);

CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL REFERENCES orders(id),
    method        TEXT NOT NULL CHECK (method IN ('card', 'convenience_store', 'bank_transfer')),
    amount_jpy    INTEGER NOT NULL,           -- 返金はマイナス金額の行として記録(SUMで実収額が出る)
    status        TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed')),
    attempted_at  TIMESTAMPTZ NOT NULL
    -- 注文との関係は1:N。試行(失敗含む)ごとに1行、UPDATEせずINSERTのみ
);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    body        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, user_id)  -- 1商品1ユーザー1レビュー
);
