// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
)

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id
FROM categories
ORDER BY parent_id NULLS FIRST, id
`

// カテゴリ全件(50件のマスタデータ)。階層はクライアント側で parent_id から組む。
// 前提: カテゴリは2階層固定(大分類10 + 子40)・件数が小さいのでページネーション不要。
//
//	階層が深くなる/件数が増えるなら、再帰CTEでツリーを組んで返す設計に変わる
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
