// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       int64
	Name     string
	ParentID pgtype.Int8
}

type Order struct {
	ID               int64
	IdempotencyKey   pgtype.UUID
	UserID           int64
	Status           string
	TotalJpy         int32
	ShippingFeeJpy   int32
	ShipToPostalCode string
	ShipToPrefecture string
	ShipToLine1      string
	ShipToLine2      pgtype.Text
	OrderedAt        pgtype.Timestamptz
}

type OrderItem struct {
	ID           int64
	OrderID      int64
	ProductID    int64
	Quantity     int32
	UnitPriceJpy int32
}

type Payment struct {
	ID          int64
	OrderID     int64
	Method      string
	AmountJpy   int32
	Status      string
	AttemptedAt pgtype.Timestamptz
}

type Product struct {
	ID          int64
	CategoryID  int64
	Name        string
	Description pgtype.Text
	PriceJpy    int32
	Stock       int32
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

type Review struct {
	ID        int64
	ProductID int64
	UserID    int64
	Rating    int16
	Body      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID         int64
	Email      string
	Name       string
	Prefecture string
	CreatedAt  pgtype.Timestamptz
}

type UserAddress struct {
	ID         int64
	UserID     int64
	Label      string
	PostalCode string
	Prefecture string
	Line1      string
	Line2      pgtype.Text
}
